title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://fearherbs1.github.io/blue-team-pad-docs

aux_links:
  Template Repository: https://github.com/fearherbs1/blue-team-pad-docs
